### ISSUE TITLE
Allow color in tree preview

### ISSUE THREAD

**Issue by quintrino** [andrewferrier/fzf-z#19]
https://github.com/andrewferrier/fzf-z/blob/76ccd9730b563e38e0b0579ba681d6a57bfad61c/fzfz#L24

Is there any way to allow color from the tree preview? 

I can see that adding in `-C` into the linked line allows it. 
```    PREVIEW_COMMAND='tree -C -L 2 -x --noreport --dirsfirst {}'```

Could we add it as a config option?

**Comment by andrewferrier** [comment]
Excellent idea! I've turned this on by default. Since I imagine some people won't like it, I've made `FZFZ_PREVIEW_COMMAND` a customizable option also so the whole preview command can be changed if desired, including its options.

**Comment by quintrino** [comment]
Awesome. Ideally I wanted to use exa
```exa {} --tree --git --long --header --color=always```
And now I can!

**Comment by andrewferrier** [comment]
You're welcome. You just introduced me to `exa`. Unfortunately it's tree mode seems exceedingly slow for me (I think maybe it pre-sorts the entire tree before output), so I think I'll give it a miss. But if it works for you, great. That's why I thought it would be helpful it make it configurable :)

Thanks for taking the time to file the request.
